// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOONXTrp44WX2qGgytrzpRHWXXHcUtBM',
    appId: '1:724099572732:web:e1fc2e9f6d7d49f6840879',
    messagingSenderId: '724099572732',
    projectId: 'n3auth-dc74c',
    authDomain: 'n3auth-dc74c.firebaseapp.com',
    storageBucket: 'n3auth-dc74c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSyhx70UbFhMfbGrqWYI5F5X1Y9hpdDw',
    appId: '1:724099572732:android:5499b4c461f4ee47840879',
    messagingSenderId: '724099572732',
    projectId: 'n3auth-dc74c',
    storageBucket: 'n3auth-dc74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP35v6QAov9Mp2YsN0OsNP8DggviHjPZU',
    appId: '1:724099572732:ios:06c871d7423009d6840879',
    messagingSenderId: '724099572732',
    projectId: 'n3auth-dc74c',
    storageBucket: 'n3auth-dc74c.firebasestorage.app',
    iosBundleId: 'com.example.n3auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP35v6QAov9Mp2YsN0OsNP8DggviHjPZU',
    appId: '1:724099572732:ios:06c871d7423009d6840879',
    messagingSenderId: '724099572732',
    projectId: 'n3auth-dc74c',
    storageBucket: 'n3auth-dc74c.firebasestorage.app',
    iosBundleId: 'com.example.n3auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLOONXTrp44WX2qGgytrzpRHWXXHcUtBM',
    appId: '1:724099572732:web:a47d8076f138e3bb840879',
    messagingSenderId: '724099572732',
    projectId: 'n3auth-dc74c',
    authDomain: 'n3auth-dc74c.firebaseapp.com',
    storageBucket: 'n3auth-dc74c.firebasestorage.app',
  );
}
